version: '3'
networks: 
  chapter:
services:
  app:
    image: node:10-alpine
    command: 'npm run dev'
    volumes:
      - .:/usr/chapter/
    working_dir: /usr/chapter/
    ports:
      - '8000:8000'
  speccy:
    image: node:10-alpine
    command: 'npm run speccy:watch'
    volumes:
      - .:/usr/chapter/
    working_dir: /usr/chapter/
    ports:
      - '8001:8001'
