version: "3.7"
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "54320:5432"
  app:
    env_file: .env
    depends_on:
      - db
    build: ./server
    working_dir: /usr/chapter/server
    environment:
      - DB_URL=db
      - EMAIL_HOST=mailhog
    ports:
      - "5000:5000"
  client:
    depends_on:
      - app
    build: ./client
    ports:
      - "3000:3000"
    working_dir: /usr/chapter/client
    # on remote environments, NEXT_PUBLIC_APOLLO_SERVER in .env needs to include the
    # remote address. e.g. https://example.com:5000
    environment: 
      NEXT_PUBLIC_APOLLO_SERVER:

