version: '3.7'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '54320:5432'
  app:
    depends_on:
      - db
    build: . 
    command: yarn dev
    working_dir: /usr/chapter
    environment:
      - DB_URL=db
    volumes:
      - .:/usr/chapter
    ports:
      - '5000:5000'
  client:
    depends_on:
      - app
    build: ./client
    ports: 
      - '3000:3000'
    command:  yarn dev
    working_dir: /usr/chapter/client
    volumes: 
      - ./client:/usr/chapter/client
