name: Cypress
on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:

jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        browsers: [chrome, firefox]
        node-version: [16.x]
    steps:
      # Remove this step after firefox launches 106
      - name: Downgrade Firefox
        run: |
          curl https://ftp.mozilla.org/pub/firefox/releases/103.0/linux-x86_64/en-US/firefox-103.0.tar.bz2 --output firefox-103.0.tar.bz2
          tar -xjf firefox-103.0.tar.bz2
          sudo mv firefox /opt/
          sudo mv /usr/bin/firefox /usr/bin/firefox_old
          sudo ln -s /opt/firefox/firefox /usr/bin/firefox
      - name: Set Action Environment Variables
        run: |
          echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Checkout Source Files
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set Chapter Environment Variables
        run: cp .env.example .env 

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: ${{ env.CYPRESS_RECORD_KEY != 0 }}
          build: npm run build
          start: npm run start:ci
          wait-on: 'http://localhost:3000, http://localhost:5000/graphql'
          browser: ${{ matrix.browsers }}

      - name: Print Cypress coverage report
        run: npm run cypress:coverage:report